name: "davidkhala/setup-rust"

branding:
  icon: 'package'
  color: 'brown'
description: Setup Rust environment
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@main
  - uses: dtolnay/rust-toolchain@master
    with:
      toolchain: stable
  
